# Generated by Django 3.0.3 on 2020-05-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=100)),
                ('second_name', models.TextField(max_length=100)),
                ('ref_number', models.TextField(max_length=100, unique=True)),
                ('course', models.TextField(choices=[('COMPUTER_SCIENCE', 'COMPUTER_SCIENCE'), ('ENGINEERING', 'ENGINEERING'), ('EDUCATION', 'EDUCATION'), ('ECONOMIC', 'ECONOMIC'), ('ARTS', 'ARTS'), ('MEDICINE', 'MEDICINE')])),
            ],
        ),
    ]
